katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import delete_task
from todolist.views import add_todolist
from todolist.views import show_json

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/',  logout_user, name='logout'),
    path('create_task/', create_task, name='create_task'),
    path('delete-task/<int:id>', delete_task, name='delete-task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_todolist, name='add_todolist'),
]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(
        User,
        on_delete= models.CASCADE,
        )
    date = models.TextField()
    title = models.TextField()
    description = models.TextField()

todolist/views.py
import operator
import datetime
from todolist.models import Task
from django.shortcuts import render, redirect
from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    task= Task.objects.filter(user= request.user)
    task = sorted(task, key= operator.attrgetter('date'))
    context = {
    'list_todo': task,
    'username': request.COOKIES['username'],
    'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

@login_required(login_url='/todolist/login/')
def show_json(request):
    data = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
@login_required(login_url="/todolist/login/")
def add_todolist(request):
    if request.method == "POST":
        title = request.POST.get("title")
        date = request.POST.get("date")
        deskripsi = request.POST.get("deskripsi")
        Task.objects.create(
            title=title, date=date, description=deskripsi, user=request.user
        )
        return JsonResponse({
            "title": title,
            "date": date,
            "deskripsi": deskripsi
        }, status=200)

def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("todolist:show_todolist"))
            response.set_cookie('username', username)
            response.set_cookie('last_login', str(datetime.datetime.now()))   
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def create_task(request):
    context = {}
    if request.method == "POST":
        title = request.POST.get("title")
        description = request.POST.get("description")
        date = request.POST.get("date")
        user = request.user
        data = Task(user = user, title=title, description=description, date=date)
        data.save()
        return redirect("todolist:show_todolist")
    return render(request, "create_task.html", context)

def delete_task(request, id):
    task = Task.objects.get(id=id)
    task.delete()
    return redirect('todolist:show_todolist')

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    response.delete_cookie('username')
    return response

todolist/templates/create_task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create Task</title>
{% endblock meta %}

{% block content %}
{% load static %}

<div class="d-flex justify-content-center mt-1">
    <h1>CREATE TASK</h1>
</div>

<div style="height: 100%;" class="d-flex justify-content-center align-items-center">
    <form method="POST" action="" style="width: 100vh;">
        {% csrf_token %}
        <div>
            <p>Date: </p>
            <input type="date" name="date" placeholder="DATE" class="form-control">
    
            <p>Title: </p>
            <input type="text" name="title" placeholder="TITTLE" class="form-control">
    
            <p>Description: </p>
            <input type="text" name="description" placeholder="DESCRIPTION" class="form-control">
        </div>

        <div class="d-flex justify-content-center mt-2 pt-4 gap-3">
            <a class="btn btn-primary btn-lg" href="{% url 'todolist:show_todolist' %}" 
            style="padding-left: 2.5rem; padding-right: 2.5rem;">Back </a>

            <button <a class="btn btn-primary btn-lg" href="{% url 'todolist:create_task' %}" type="submit" value="submit"
            style="padding-left: 2.5rem; padding-right: 2.5rem;"> </a>Submit</button>
        </div>
    </form>
</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}
{% block content %}
{% load static %}

<section class="vh-100">
    <div class="container-fluid h-custom">
      <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-md-9 col-lg-6 col-xl-5">
            <img src="{% static 'media/a4.png' %}" width="650" height="750"
                alt="home">
        </div> 
        <div class="col-md-8 col-lg-6 col-xl-4 offset-xl-1">
            <div class = "login">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="divider d-flex align-items-center my-2">
                        <p class="text-center fw-bold mx-1 mb-3">Login</p>
                      </div>

                    <div class="form-outline mb-4">
                        <input type="text" id="username" name = "username" class="form-control form-control-lg"
                        placeholder="Enter a valid username" />
                        <label class="form-label">Username</label>
                    </div>

                    <div class="form-outline mb-3">
                        <input type="password" id="password" name = "password" class="form-control form-control-lg"
                        placeholder="Enter password" />
                        <label class="form-label">Password</label>
                    </div>

                    <div class="text-center text-lg-start mt-4 pt-2">
                        <button type="submit" value="Login" class="btn btn-primary btn-lg"
                        style="padding-left: 2.5rem; padding-right: 2.5rem;"> Login </button>
                        <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="{% url 'todolist:register' %}"
                            class="link-danger">Register</a></p>
                    </div>
                </form>

                {% if messages %}
                    <ul>
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}     
            </div>
        </div>
    </div>
</section>
{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}
{% block content %}
{% load static %}

<div style="background-image: url('{% static "media/a5.png" %}'); height: 100vh;">
    <div class = "container-fluid px-2 py-5 ">
        <div class="row d-flex justify-content-center align-items-center">
            <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                <div class="card" style="border-radius: 30px">
                    <div class="card-body p-5">
                        <h2 class="text-uppercase text-center mb-5">Registration form</h2>
                        <div class="row d-flex justify-content-center align-items-center h-100">
                            <p id="description">Please fill it!</p>
                            <form method="POST" >  
                                {% csrf_token %}  
                                <div class="row mb-4">
                                    <label for="{{form.username.id_for_label}}" class="col-sm-4 col-form-label">Username: </label>
                                    <div class="col-sm-2">
                                        {{form.username}}
                                    </div>
                                </div>

                                <div class="row mb-4">
                                    <label for="{{form.password1.id_for_label}}" class="col-sm-4 col-form-label">Password: </label>
                                    <div class="col-sm-2">
                                        {{form.password1}}
                                    </div>
                                </div>
                                
                                <div class="row mb-1">
                                    <label for="{{form.password1.id_for_label}}" class="col-sm-4 col-form-label">Confirmation password: </label>
                                    <div class="col-sm-2">
                                        {{form.password2}}
                                    </div>
                                </div>

                                <div class="d-flex justify-content-center ">
                                    <button type="submit" value="Login" class="btn btn-primary btn-lg"
                                    style="padding-left: 2.5rem; padding-right: 2.5rem;">Register</button>
                                </div>
                            </form>
                            <div class="d-flex justify-content-center fw-bold mt-2 pt-1 mb-0">Already have an account? <a href="{% url 'todolist:login' %}"
                                class="link-danger">Login here </a></div>
                            </div>
                        </div>  
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block content %}
{% load static %}

<script>
  $(document).ready(function(){
      $.getJSON("{% url 'todolist:show_json' %}", function(data){
          $.each(data, function(index,value){
            console.log(value)
              $("#todolist").append(
                `<div class="card text-center zoom">
                  <div class="card-header card-bg-rv">Date: ${value.fields.date}</div>
                    <div class="image-box card-bg-rv">
                      <img src= "/static/media/a3.png" height="200"">
                      <div class="card responsive-card">
                        <div class="card-body card-bg-rv">
                          <h5 class="card-title"> ${value.fields.title}</h5>
                          <p class="card-text"> ${value.fields.description} </p>
                          <a href="#" class="btn btn-primary">Delete task</a>
                        </div>
                      </div>
                    </div>
                  </div>  
                </div>`    
              )
          })
      })
    $("#form-ajax").on("submit",function(e) {
      e.preventDefault() 
      let date = $("#date").val();
      let title = $("#title").val();
      let deskripsi = $("#deskripsi").val();
      $.ajax({
        method: "POST",
        url: "/todolist/add/",
        data: {"date":date, "title":title, "deskripsi":deskripsi},
      }).done(function(resp) {
        console.log(resp)
        $("#todolist").append(
          `<div class="card text-center zoom">
            <div class="card-header card-bg-rv">Date: ${resp.date}</div>
              <div class="image-box card-bg-rv">
                <img src= "/static/media/a3.png" height="200"">
                <div class="card responsive-card">
                  <div class="card-body card-bg-rv">
                    <h5 class="card-title"> ${resp.title}</h5>
                    <p class="card-text"> ${resp.deskripsi} </p>
                    <a id="btn-delete" class="btn btn-primary">Delete task</a>
                  </div>
                </div>
              </div>
            </div>  
          </div>`    
        )
        $("#modal-todolist").modal("toggle")
      });
    })
  })
</script>

<title>To Do List</title>

<nav class="navbar navbar-expand-lg bg-info navbar-light responsive-navbar">
  <div class="container-fluid">
    <a class="navbar-brand">To Do List</a>
      <ul class="navbar-nav d-flex flex-wrap me-1">
        <li lass="nav-item me-3 me-lg-1">
          <a class="nav-link text-white">
            <img src="{% static "media/a2.png" %}"
                 class="rounded-circle"
                 height="22"
                 alt="jisoo"
                 loading="lazy" />
            {{username}}
          </a>
        </li>
        <li class="nav-item me-3 me-lg-1">
            <a class="nav-link text-white" href="{% url 'todolist:logout' %}"><i class="fas fa-cog mx-1"></i> Log out</a>
        </li>
    </ul>
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#modal-todolist" data-bs-whatever= "@mdo" id="create-task">Create task</button>
  </div>
</nav>

<div class="d-flex justify-content-center m-auto">
  <h5>Sesi terakhir login: {{ last_login }}</h5>
</div>

<div class="d-flex flex-wrap justify-content-center align-items-center gap-3 responsive-container mt-4" id="todolist">
</div>

<div class="modal fade" id="modal-todolist" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5">Create task</h1>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <form id="form-ajax" action = "/todolist/add/">
          {% csrf_token %}
          <div class="mb-3">
            <label class="col-form-label">Date:</label>
            <input type="date" class="form-control" id="date" required>
          </div>
          <div class="mb-3">
            <label class="col-form-label">Title:</label>
            <input type="text" class="form-control" id="title" required>
          </div>
          <div class="mb-3">
            <label class="col-form-label">Description:</label>
            <textarea class="form-control" id="deskripsi" required></textarea>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            <button type="submit" value="submit" class="btn btn-primary" id="btn_submit">Submit</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}